
{{- if .Values.jobs.migrate -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-migratejob
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      restartPolicy: Never
      initContainers:
      - name: {{ .Chart.Name }}-migratedelay
        image: busybox:1.28
        command: ['sh', '-c', 'sleep 30']
      
      containers:
      - name: {{ .Chart.Name }}-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["python", "manage.py", "migrate"]

        env:
          # - name: DB_HOST
          #   value: {{ template "postgres.fullname" . }}
          # - name: DB_NAME
          #   value: {{ .Values.postgresql.postgresqlDatabase }}
          # - name: DB_PORT
          #   value: "5432"
          # - name: DB_USER
          #   value: {{ .Values.postgresql.postgresqlUsername }}
          # - name: DB_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ template "postgres.fullname" . }}              
          #       key:  postgresql-password
          # - name: DB_HOST
          #   value: {{ template "postgres.fullname" . }}
          - name: DB_HOST
            value: {{ .Values.postgresql.postgresqlFullname }}
          - name: DB_NAME
            value: {{ .Values.postgresql.postgresqlDatabase }}
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: {{ .Values.postgresql.postgresqlUsername }}
          # - name: DB_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ template "postgres.fullname" . }}              
          #       key:  postgresql-password
          - name: DB_PASSWORD
            value: {{ .Values.postgresql.postgresqlPassword }}


{{- end }}
