replicaCount: 1

image:
  repository: jfmatth/aim-django
  tag: v1.06
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true

  # annotations: 
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  #   cert-manager.io/cluster-issuer: issuer-production
  #   nginx.ingress.kubernetes.io/force-ssl-redirect	: "true"

  hosts:
    - host: test.192.168.1.200.nip.io
      paths: ['/']

  # tls: 
  # - hosts:
  #   - qa.stocksonthebeach.com
  #   secretName: qa-sotb-com


postgresql:
  postgresqlFullname: sotb-v1-test.database
  postgresqlDatabase: sotb
  postgresqlUsername: adminsyymgnc
  postgresqlPassword: changeme

  # image:
  #   tag: 9.6.18

  # resources:
  #   requests:
  #     cpu: 250m
  #     memory: 256Mi
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi

timestamp: "new"

jobs:
  loadprices: true
  migrate: false
  ftplogin: changeme
  ftppass: changeme
  crontab: "0 23 * * *"
  emailuser: changeme
  emailpassword: changeme
