---
apiVersion: v1
kind: Namespace
metadata:
  name: blog-jfmatth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"

  name: blog-jfmatth
  namespace: blog-jfmatth

  labels:
    app: static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site

  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: blog-jfmatth
        image: jfmatth/blog-jfmatth:7c1efb4ab8770b15467a41b06bde5d5905d4730a
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog-jfmatth
  namespace: blog-jfmatth
  labels:
    app: static-site
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static-site
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blog-jfmatth
  namespace: blog-jfmatth
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: "/"
        # traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
  - host: master.mshome.net
    http:
      paths:
      - path: /blog
        backend:
          serviceName: blog-jfmatth
          servicePort: 80
