---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: local
  namespace: default
  annotations:
    fluxcd.io/locked_user: John Matthew <john@compunique.com>
    fluxcd.io/locked: 'true'
spec:
  chart:
    git: https://github.com/jfmatth/K8s-flux.git
    ref: master
    path: charts/aim-local

    values:
      jobs:
        migrate: false

