---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: k8sprod

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aim-k8sprod
  namespace: k8sprod
  annotations:
    fluxcd.io/automated: "true"
spec:
  rollback:
    enable: true

  chart:
    git: https://github.com/jfmatth/K8s-flux.git
    ref: master
    path: charts/aim-k8sprod

#  Chart value overrides can go here
#  Override the jobs section from our Helm chart
  values:
    jobs:
      migrate: false
      loadprices: true
      ftplogin: changeme
      ftppass: changeme
      crontab: "0 22 * * *"
      emailuser: changeme
      emailpassword: changeme
 
    image:
      repository: jfmatth/aim-django
      tag: v1.01
      pullPolicy: Always

    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: issuer-production
        nginx.ingress.kubernetes.io/force-ssl-redirect	: "true"
    
      hosts:
        - host: qa.stocksonthebeach.com
          paths: ['/']
    
      tls: 
      - hosts:
        - qa.stocksonthebeach.com
        secretName: qa-sotb-com