dependencies:
    # - name: postgresql
    #   version: 7.7.2
    #   repository: https://kubernetes-charts.storage.googleapis.com
    
    - name: postgresql
      version: 8.7.4
      repository: https://charts.bitnami.com/bitnami