---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
    apiVersion: helm.fluxcd.io/v1
    kind: HelmRelease
    metadata:
      name: cert-manager
      namespace: cert-manager
    spec:
        chart:
          repository: https://charts.jetstack.io/
          name: cert-manager
          version: v0.15.2
        values:
          installCRDs: true
